/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.2).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.touresbalon.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.context.request.NativeWebRequest;

import com.touresbalon.service.domain.ClientesGETAllRS;
import com.touresbalon.service.domain.ClientesGETByIdRs;
import com.touresbalon.service.domain.ClientesPCTRq;
import com.touresbalon.service.domain.ClientesPCTRs;
import com.touresbalon.service.domain.ClientesPSTRq;
import com.touresbalon.service.domain.ClientesPSTRs;

import javax.validation.Valid;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2020-04-09T13:17:10.375-05:00[America/Bogota]")

//@Validated
//@Api(value = "clientes", description = "the clientes API")
public interface IClientesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }


    public ResponseEntity<Void> clientesDEL(@ApiParam(value = "Id de cliente",required=true) @PathVariable("idCliente") Long idCliente);


    public ClientesGETAllRS clientesGETAll(@ApiParam(value = "El número de clientes a omitir antes de comenzar a recopilar el conjunto de resultados")
                                           @Valid @RequestParam(value = "offset", required = false) Integer offset,
                                           @ApiParam(value = "El número de clientes a retornar") @Valid @RequestParam(value = "limit", required = false) Integer limit,
                                           @ApiParam(value = "Nombres para consultar") @Valid @RequestParam(value = "nombres", required = false) String nombres,
                                           @ApiParam(value = "Apellidos para consultar") @Valid @RequestParam(value = "apellidos", required = false) String apellidos,
                                           @ApiParam(value = "Identificacion para consultar") @Valid @RequestParam(value = "identificacion", required = false) String identificacion,
                                           @ApiParam(value = "Tipo Identificacion para consultar") @Valid @RequestParam(value = "tipoIdentificacion", required = false) String tipoIdentificacion,
                                           @ApiParam(value = "Estado del cliente.", allowableValues = "ACTIVO, INACTIVO")
    @Valid @RequestParam(value = "estado", required = false) String estado);


    public ClientesGETByIdRs clientesGETById(@ApiParam(value = "Id de cliente",required=true) @PathVariable("id") Long id);



    public ResponseEntity<ClientesPCTRs> clientesPCT(@ApiParam(value = "Id de cliente", required = true) @PathVariable("id") Long id,@ApiParam(value = "Cliente a actualizar"  )  @Valid @RequestBody ClientesPCTRq clientesPCTRq);

    public ResponseEntity<ClientesPSTRs> clientesPST(@ApiParam(value = "Cliente a registrar"  )  @Valid @RequestBody ClientesPSTRq clientesPSTRq);

}
