--Insert de países---------------------------------------------------------------------------------------------------------
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Andorra',020);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Emiratos Árabes Unidos',784);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Afganistán',004);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Antigua y Barbuda',028);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Anguila',660);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Albania',008);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Armenia',051);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Antillas Neerlandesas',530);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Angola',024);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Antártida',010);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Argentina',032);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Samoa Americana',016);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Austria',040);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Australia',036);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Aruba',533);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Áland',248);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Azerbaiyán',031);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bosnia y Herzegovina',070);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Barbados',052);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bangladesh',050);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bélgica',056);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Burkina Faso',854);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bulgaria',100);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bahréin',048);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Burundi',108);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Benin',204);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('San Bartolomé',652);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bermudas',060);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Brunéi',096);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bolivia',068);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Brasil',076);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bahamas',044);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Bhután',064);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Isla Bouvet',074);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Botsuana',072);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Belarús',112);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Belice',084);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Canadá',124);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Cocos',166);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('República Centro-Africana',140);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Congo',178);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Suiza',756);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Costa de Marfil',384);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Cook',184);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Chile',152);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Camerún',120);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('China',156);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Colombia',170);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Costa Rica',188);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Cuba',192);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Cabo Verde',132);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Christmas',162);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Chipre',196);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('República Checa',203);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Alemania',276);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Yibuti',262);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Dinamarca',208);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Domínica',212);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('República Dominicana',214);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Argel',012);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Ecuador',218);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Estonia',233);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Egipto',818);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Sahara Occidental',732);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Eritrea',232);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('España',724);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Etiopía',231);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Finlandia',246);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Fiji',242);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Malvinas',238);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Micronesia',583);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Faroe',234);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Francia',250);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Gabón',266);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Reino Unido',826);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Granada',308);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Georgia',268);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guayana Francesa',254);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guernsey',831);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Ghana',288);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Gibraltar',292);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Groenlandia',304);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Gambia',270);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guinea',324);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guadalupe',312);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guinea Ecuatorial',226);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Grecia',300);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Georgia del Sur e Islas Sandwich del Sur',239);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guatemala',320);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guam',316);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guinea-Bissau',624);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Guayana',328);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Hong Kong',344);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Heard y McDonald',334);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Honduras',340);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Croacia',191);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Haití',332);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Hungría',348);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Indonesia',360);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Irlanda',372);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Israel',376);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Isla de Man',833);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('India',356);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Territorio Británico del Océano Índico',086);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Irak',368);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Irán',364);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islandia',352);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Italia',380);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Jersey',832);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Jamaica',388);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Jordania',400);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Japón',392);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Kenia',404);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Kirguistán',417);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Camboya',116);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Kiribati',296);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Comoros',174);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('San Cristóbal y Nieves',659);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Corea del Norte',408);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Corea del Sur',410);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Kuwait',414);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Caimán',136);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Kazajstán',398);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Laos',418);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Líbano',422);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Santa Lucía',662);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Liechtenstein',438);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Sri Lanka',144);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Liberia',430);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Lesotho',426);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Lituania',440);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Luxemburgo',442);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Letonia',428);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Libia',434);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Marruecos',504);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mónaco',492);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Moldova',498);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Montenegro',499);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Madagascar',450);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Marshall',584);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Macedonia',807);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mali',466);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Myanmar',104);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mongolia',496);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Macao',446);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Martinica',474);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mauritania',478);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Montserrat',500);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Malta',470);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mauricio',480);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Maldivas',462);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Malawi',454);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('México',484);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Malasia',458);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mozambique',508);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Namibia',516);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nueva Caledonia',540);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Níger',562);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Norkfolk',574);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nigeria',566);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nicaragua',558);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Países Bajos',528);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Noruega',578);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nepal',524);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nauru',520);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Niue',570);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Nueva Zelanda',554);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Omán',512);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Panamá',591);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Perú',604);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Polinesia Francesa',258);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Papúa Nueva Guinea',598);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Filipinas',608);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Pakistán',586);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Polonia',616);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('San Pedro y Miquelón',666);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Pitcairn',612);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Puerto Rico',630);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Palestina',275);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Portugal',620);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Palaos',585);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Paraguay',600);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Qatar',634);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Reunión',638);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Rumanía',642);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Serbia y Montenegro',688);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Rusia',643);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Ruanda',646);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Arabia Saudita',682);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Solomón',090);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Seychelles',690);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Sudán',736);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Suecia',752);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Singapur',702);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Santa Elena',654);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Eslovenia',705);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Svalbard y Jan Mayen',744);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Eslovaquia',703);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Sierra Leona',694);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('San Marino',674);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Senegal',686);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Somalia',706);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Surinam',740);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Santo Tomé y Príncipe',678);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('El Salvador',222);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Siria',760);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Suazilandia',748);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Turcas y Caicos',796);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Chad',148);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Territorios Australes Franceses',260);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Togo',768);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tailandia',764);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tanzania',834);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tayikistán',762);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tokelau',772);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Timor-Leste',626);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Turkmenistán',795);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Túnez',788);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tonga',776);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Turquía',792);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Trinidad y Tobago',780);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Tuvalu',798);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Taiwán',158);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Ucrania',804);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Uganda',800);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Estados Unidos de América',840);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Uruguay',858);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Uzbekistán',860);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Ciudad del Vaticano',336);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('San Vicente y las Granadinas',670);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Venezuela',862);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Vírgenes Británicas',092);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Islas Vírgenes de los Estados Unidos de América',850);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Vietnam',704);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Vanuatu',548);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Wallis y Futuna',876);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Samoa',882);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Yemen',887);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Mayotte',175);
INSERT INTO public."Pais"("Nombre", "Codigo") VALUES ('Sudáfrica',710);
