/*
 * Convenios API
 *
 * Este es el API de Convenios para Toures Balon
 *
 * OpenAPI spec version: 1.0.0
 * Contact: touresbalon@archetype.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations.Schema;

namespace Javeriana.Convenios.Api.Models
{
    /// <summary>
    /// Ciudad
    /// </summary>
    //[DataContract]
    [Table("Ciudad")]
    public partial class Ciudad : IEquatable<Ciudad>
    {
        /// <summary>
        /// Código de la ciudad.
        /// </summary>
        /// <value>Código de la ciudad.</value>
        //[DataMember(Name="codigo")]
        [Required(ErrorMessage = "El código de la ciudad es obligatorio")]
        [Key]
        public int Codigo { get; set; }

        /// <summary>
        /// Nombre de la ciudad.
        /// </summary>
        /// <value>Nombre de la ciudad.</value>
        //[DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets Pais
        /// </summary>
        //[DataMember(Name="pais")]
        public Pais Pais { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Ciudad {\n");
            sb.Append("  Codigo: ").Append(Codigo).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Pais: ").Append(Pais).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Ciudad)obj);
        }

        /// <summary>
        /// Returns true if Ciudad instances are equal
        /// </summary>
        /// <param name="other">Instance of Ciudad to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Ciudad other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Codigo == other.Codigo ||
                    Codigo.Equals(other.Codigo)
                ) && 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) && 
                (
                    Pais == other.Pais ||
                    Pais != null &&
                    Pais.Equals(other.Pais)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (Pais != null)
                    hashCode = hashCode * 59 + Pais.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Ciudad left, Ciudad right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Ciudad left, Ciudad right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
